"use client";
import profilePic from "../public/images/profile/developer-pic-1.webp";
import React from "react";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import lightBulb from "../public/images/svgs/miscellaneous_icons_1.svg";
import HireMe from "@/components/HireMe";
import Layout from "@/components/Layout";
import Head from "next/head";
import { motion } from "framer-motion";

const Home = () => {
  return (
    <motion.div
      className="h-full "
      initial={{ y: "-150vh" }}
      animate={{ y: "0%" }}
      transition={{ duration: 1 }}
    >
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen 2xl:">
        <Layout className="pt-0 max-md:pt-16 max-sm:pt-8  ">
          <div className="flex items-center justify-between w-full max-lg:flex-col">
            <div className="w-1/2 max-md:w-full">
              <Image
                src={profilePic}
                alt="Indhu Profile Picture"
                width={500}
                height={500}
                className="w-full h-auto max-lg:hidden max-md:inline-block max-md:w-full"
                priority
                layout="intrinsic"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center max-lg:w-full max-lg:text-center">
              <AnimatedText
                text="Bringing Ideas to Life Through Code and Functionality."
                className="!text-6xl !text-left max-xl:!text-5xl max-lg:!text-center max-lg:!text-6xl max-md:!text-5xl max-sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium max-md:text-sm max-sm:text-xs ">
                As an aspiring frontend developer, I focus on building
                responsive, user-friendly websites using clean, efficient code.
                My goal is to turn concepts into functional, accessible web
                experiences. Explore my projects to see how I&apos;m growing my
                skills in HTML, CSS, JavaScript, and modern frontend tools like
                React.js.
              </p>
              <div className="items-center  flex mt-2 self-start max-lg:self-center">
                <Link
                  href="/Indhu_Jeyaraman_CV.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark max-md:p-2 max-md:px-4 max-md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                <Link
                  href="mailto:indhujayk@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline transition-transform duration-200 hover:-translate-y-0.5 max-md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 w-24 inline-block max-md:hidden">
          <Image src={lightBulb} alt="" className="w-full h-auto max-lg:hidden" />
        </div>
      </main>
    </motion.div>
  );
};

export default Home;
